### ISSUE TITLE
can't run the program

### ISSUE THREAD

**Issue by KoleckOLP** [alkihis/archive-explorer-web#28]
I installed node.js + npn
cloned the repo
ran `npm install`
and than ran `npm start`
and got this error?

```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\Users\test\Downloads\archive-explorer-web\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\test\Downloads\archive-explorer-web\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\test\Downloads\archive-explorer-web\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\test\Downloads\archive-explorer-web\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\test\Downloads\archive-explorer-web\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\test\Downloads\archive-explorer-web\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\test\Downloads\archive-explorer-web\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\test\Downloads\archive-explorer-web\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\test\Downloads\archive-explorer-web\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\Users\test\Downloads\archive-explorer-web\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\test\Downloads\archive-explorer-web\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\test\Downloads\archive-explorer-web\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\test\Downloads\archive-explorer-web\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\test\Downloads\archive-explorer-web\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\test\Downloads\archive-explorer-web\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\test\Downloads\archive-explorer-web\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\test\Downloads\archive-explorer-web\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v22.4.1
```

is my npm and node.js too new or am I missing something?

**Comment by KoleckOLP** [comment]
Oh yeah this project probably does not work on node.js newer than V16, confirmed working on 16.20.2 x68

**Comment by alkihis** [comment]
Project hasn't been updated since 4 years (except for one small change), so unfortunately it cannot run Node 16+ :(
I've tried to update to a newer version of React to allow compilation on newer Node version, but this is a dependency nightmare
